// Package cashierAdmin Code generated by swaggo/swag. DO NOT EDIT
package cashierAdmin

import "github.com/swaggo/swag"

const docTemplatecashierAdmin = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfocashierAdmin holds exported Swagger Info so clients can modify it
var SwaggerInfocashierAdmin = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "cashierAdmin",
	SwaggerTemplate:  docTemplatecashierAdmin,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocashierAdmin.InstanceName(), SwaggerInfocashierAdmin)
}
