debug: true
server:
  api:
    port: "8080"
    host: "0.0.0.0"
  merchant:
    port: "8081"
    host: "0.0.0.0"
  admin:
    port: "8082"
    host: "0.0.0.0"
database:
  dsn: "host=localhost user=inpayos password=password dbname=inpayos_dev port=5432 sslmode=disable TimeZone=Asia/Shanghai"
  max_idle_conns: 5
  max_open_conns: 50
  conn_max_lifetime: "30m"
  conn_max_idle_time: "5m"