debug: true
server:
  host: "0.0.0.0"
  port: "8081"
database:
  dsn: "root:password@tcp(localhost:3306)/inpayos_dev?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conns: 5
  max_open_conns: 50
  conn_max_lifetime: "30m"
  conn_max_idle_time: "5m"