# InPayOS Production Configuration
# 支付网关生产环境配置

debug: false
environment: "production"

# 服务器配置
server:
  # OpenAPI - 商户支付网关主接口
  openapi:
    host: "0.0.0.0"
    port: "8080"
    read_timeout: "30s"
    write_timeout: "30s"
    
  # CashierAPI - 收银渠道服务接口  
  cashier_api:
    host: "0.0.0.0"
    port: "8081"
    read_timeout: "30s"
    write_timeout: "30s"
    
  # MerchantAPI - 商户管理后台接口
  merchant_api:
    host: "0.0.0.0"
    port: "8082"
    read_timeout: "30s"
    write_timeout: "30s"
    
  # CashierAdminAPI - 收银团队管理后台接口
  cashier_admin_api:
    host: "0.0.0.0"
    port: "8083"
    read_timeout: "30s"
    write_timeout: "30s"
    
  # AdminAPI - 全局管理后台接口
  admin_api:
    host: "0.0.0.0"
    port: "8084"
    read_timeout: "30s"
    write_timeout: "30s"

# 数据库配置
database:
  dsn: "host={{SYSTEM_INTERNAL_IP}} user=inpayos password=${DB_PASSWORD} dbname=inpayos_prod port=5432 sslmode=require TimeZone=Asia/Shanghai"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "60m"
  conn_max_idle_time: "10m"

# Redis配置
redis:
  host: "{{SYSTEM_INTERNAL_IP}}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 20
  min_idle_conns: 5

# 日志配置
log:
  level: "info"
  format: "json"
  output: "file"
  file_path: "/logs/inpayos.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

# JWT配置
jwt:
  secret: "${JWT_SECRET}"
  expires_in: "24h"
  refresh_expires_in: "168h"

# 加密配置
encryption:
  key: "${ENCRYPTION_KEY}"
  
# 支付渠道配置
channels:
  # Cashier收银渠道
  cashier:
    enabled: true
    timeout: "30s"
    retry_count: 3
    
  # 第三方API渠道
  third_party:
    enabled: true
    timeout: "30s"
    retry_count: 3

# 国际化配置
i18n:
  default_language: "en"
  languages:
    - "en"
    - "zh"
    - "id"
    - "th"
    - "vi"

# 监控配置
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"
  
# 安全配置
security:
  api_rate_limit: 10000
  cors_origins:
    - "https://inpayos.com"
    - "https://admin.inpayos.com"
    - "https://merchant.inpayos.com"
  trusted_proxies:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"