// Package cashier Code generated by swaggo/swag. DO NOT EDIT
package cashier

import "github.com/swaggo/swag"

const docTemplatecashier = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfocashier holds exported Swagger Info so clients can modify it
var SwaggerInfocashier = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "cashier",
	SwaggerTemplate:  docTemplatecashier,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocashier.InstanceName(), SwaggerInfocashier)
}
