// Package cashier_admin Code generated by swaggo/swag. DO NOT EDIT
package cashier_admin

import "github.com/swaggo/swag"

const docTemplatecashieradmin = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfocashieradmin holds exported Swagger Info so clients can modify it
var SwaggerInfocashieradmin = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "cashieradmin",
	SwaggerTemplate:  docTemplatecashieradmin,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocashieradmin.InstanceName(), SwaggerInfocashieradmin)
}
