definitions:
  inpayos_internal_protocol.CashierTeam:
    type: object
  inpayos_internal_protocol.MapData:
    additionalProperties: {}
    type: object
  inpayos_internal_protocol.PageResult:
    properties:
      attach:
        additionalProperties: {}
        description: 附加数据
        type: object
      count:
        description: 总记录数
        type: integer
      current:
        description: 当前页码
        type: integer
      records:
        description: 记录列表
      result_type:
        description: 数据类型
        type: string
      size:
        description: 每页记录数
        type: integer
      total:
        description: 总页数
        type: integer
    type: object
  inpayos_internal_protocol.Result:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
    type: object
  inpayos_internal_protocol.Transaction:
    properties:
      account_name:
        type: string
      account_no:
        description: 账户信息
        type: string
      account_type:
        type: string
      actual_amount:
        type: string
      amount:
        type: string
      bank_code:
        type: string
      bank_name:
        type: string
      cancel_failed_result:
        type: string
      cancel_reason:
        type: string
      canceled_at:
        description: 取消信息
        type: integer
      cashier_id:
        description: 收银员信息
        type: string
      ccy:
        description: 金额信息
        type: string
      channel_account:
        type: string
      channel_code:
        type: string
      channel_fee_amount:
        type: string
      channel_fee_ccy:
        type: string
      channel_fee_usd_amount:
        type: string
      channel_fee_usd_rate:
        type: string
      channel_group:
        type: string
      channel_status:
        type: string
      channel_trx_id:
        description: 渠道信息
        type: string
      completed_at:
        type: integer
      confirmed_at:
        description: 时间戳
        type: integer
      country:
        type: string
      created_at:
        type: integer
      detail:
        additionalProperties: {}
        type: object
      did:
        type: string
      email:
        type: string
      expired_at:
        type: integer
      failure_reason:
        type: string
      fee_amount:
        type: string
      fee_ccy:
        description: 费用信息
        type: string
      fee_usd_amount:
        type: string
      fee_usd_rate:
        type: string
      flow_no:
        description: 流程信息
        type: string
      id:
        description: 基础交易信息
        type: integer
      last_refunded_at:
        type: integer
      link:
        type: string
      metadata:
        allOf:
        - $ref: '#/definitions/inpayos_internal_protocol.MapData'
        description: 扩展信息
      mid:
        type: string
      notify_url:
        type: string
      ori_flow_no:
        type: string
      ori_req_id:
        type: string
      ori_trx_id:
        description: 原始交易信息
        type: string
      phone:
        type: string
      pkg:
        type: string
      product_id:
        type: string
      reason:
        type: string
      refunded_amount:
        type: string
      refunded_count:
        description: 退款信息
        type: integer
      refunded_usd_amount:
        type: string
      remark:
        type: string
      req_id:
        type: string
      res_code:
        type: string
      res_msg:
        type: string
      return_url:
        type: string
      settle_id:
        type: string
      settle_status:
        description: 结算信息
        type: string
      settled_at:
        type: integer
      status:
        description: 状态信息
        type: string
      tid:
        type: string
      trx_app:
        type: string
      trx_id:
        type: string
      trx_method:
        description: 交易方式和模式
        type: string
      trx_mode:
        type: string
      trx_type:
        type: string
      updated_at:
        type: integer
      usd_amount:
        type: string
      user_id:
        type: string
      user_ip:
        description: 用户信息
        type: string
      version:
        type: integer
    type: object
  inpayos_internal_services.CashierTeamRegisterRequest:
    properties:
      company_name:
        description: 公司名称
        type: string
      email:
        description: 邮箱
        type: string
      nickname:
        description: 昵称
        minLength: 2
        type: string
      password:
        description: 密码
        minLength: 8
        type: string
      phone:
        description: 联系电话
        type: string
      reg_ip:
        description: 注册IP
        type: string
      region:
        description: 地区
        type: string
      verify_code:
        description: 验证码
        type: string
    required:
    - company_name
    - email
    - nickname
    - password
    - phone
    - verify_code
    type: object
  inpayos_internal_services.TodayStats:
    properties:
      pendingCount:
        description: 待处理交易数
        type: integer
      successCount:
        description: 成功交易数
        type: integer
      successRate:
        description: 成功率（百分比）
        type: number
      totalAmount:
        description: 总金额
        type: string
      totalCount:
        description: 总交易数
        type: integer
    type: object
  internal_handlers.AuthRequest:
    properties:
      code:
        example: "123456"
        type: string
      email:
        example: user@example.com
        type: string
      password:
        example: password
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIs...
        type: string
    type: object
  internal_handlers.BindG2FAReq:
    properties:
      code:
        description: G2FA验证码
        type: string
      verify_code:
        description: 邮箱验证码
        type: string
    required:
    - code
    type: object
  internal_handlers.ChangePasswordReq:
    properties:
      new_password:
        description: 新密码
        minLength: 6
        type: string
    required:
    - new_password
    type: object
  internal_handlers.ResetPasswordReq:
    properties:
      email:
        description: 邮箱地址
        type: string
      verification_code:
        description: 验证码
        type: string
    required:
    - email
    - verification_code
    type: object
  internal_handlers.SendVerifyCodeReq:
    properties:
      email:
        description: 邮箱地址
        type: string
      type:
        description: 验证码类型
        type: string
    required:
    - email
    - type
    type: object
  internal_handlers.VerifyCodeReq:
    properties:
      code:
        description: 验证码
        type: string
      email:
        description: 邮箱地址
        type: string
      type:
        description: 验证码类型
        enum:
        - register
        - login
        - reset
        type: string
    required:
    - code
    - email
    - type
    type: object
info:
  contact: {}
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: 处理登陆认证并返回token
      parameters:
      - description: 认证请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.AuthRequest'
      produces:
      - application/json
      responses: {}
      summary: 登陆授权认证
      tags:
      - CashierAdmin
  /cashiers/detail:
    post:
      consumes:
      - application/json
      description: 获取指定出纳员的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/inpayos_internal_protocol.Result'
            - properties:
                data:
                  $ref: '#/definitions/inpayos_internal_protocol.CashierTeam'
              type: object
      summary: 获取出纳员详情
      tags:
      - CashierAdmin
  /cashiers/list:
    post:
      consumes:
      - application/json
      description: 分页获取出纳员列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/inpayos_internal_protocol.Result'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/inpayos_internal_protocol.PageResult'
                  - properties:
                      list:
                        items:
                          $ref: '#/definitions/inpayos_internal_protocol.CashierTeam'
                        type: array
                    type: object
              type: object
      summary: 获取出纳员列表
      tags:
      - CashierAdmin
  /info:
    post:
      consumes:
      - application/json
      description: 获取当前登录收银员的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/inpayos_internal_protocol.Result'
            - properties:
                data:
                  $ref: '#/definitions/inpayos_internal_protocol.CashierTeam'
              type: object
        "401":
          description: 认证失败
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      security:
      - BearerAuth: []
      summary: 获取收银员信息
      tags:
      - CashierAdmin
  /logout:
    post:
      consumes:
      - application/json
      description: 收银员登出接口
      produces:
      - application/json
      responses:
        "200":
          description: 登出成功
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      security:
      - BearerAuth: []
      summary: 收银员登出
      tags:
      - CashierAdmin
  /merchant/g2fa/bind:
    post:
      consumes:
      - application/json
      description: 绑定收银员的二次验证
      parameters:
      - description: 绑定信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.BindG2FAReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 收银员绑定G2FA
      tags:
      - CashierAdmin
  /merchant/g2fa/new:
    post:
      consumes:
      - application/json
      description: 为收银员生成新的G2FA密钥
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 生成新的G2FA密钥
      tags:
      - CashierAdmin
  /password/change:
    post:
      consumes:
      - application/json
      description: 商户登录后修改密码
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 修改密码请求
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.ChangePasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 修改密码
      tags:
      - CashierAdmin
  /password/reset:
    post:
      consumes:
      - application/json
      description: 通过邮箱验证码重置密码，新密码将发送到邮箱
      parameters:
      - description: 重置密码请求
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.ResetPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 重置密码
      tags:
      - CashierAdmin
  /register:
    post:
      consumes:
      - application/json
      description: 邮箱注册新用户
      parameters:
      - description: 注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/inpayos_internal_services.CashierTeamRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 商户注册
      tags:
      - CashierAdmin
  /transactions/detail:
    post:
      consumes:
      - application/json
      description: 获取指定交易ID的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/inpayos_internal_protocol.Result'
            - properties:
                data:
                  $ref: '#/definitions/inpayos_internal_protocol.Transaction'
              type: object
      summary: 获取交易详情
      tags:
      - CashierAdmin
  /transactions/list:
    post:
      consumes:
      - application/json
      description: 分页获取交易列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/inpayos_internal_protocol.Result'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/inpayos_internal_protocol.PageResult'
                  - properties:
                      list:
                        items:
                          $ref: '#/definitions/inpayos_internal_protocol.Transaction'
                        type: array
                    type: object
              type: object
      summary: 获取交易列表
      tags:
      - CashierAdmin
  /transactions/today-stats:
    post:
      consumes:
      - application/json
      description: 获取指定交易类型的今日统计数据
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/inpayos_internal_protocol.Result'
            - properties:
                data:
                  $ref: '#/definitions/inpayos_internal_services.TodayStats'
              type: object
      summary: 获取今日交易统计
      tags:
      - CashierAdmin
  /verifycode/send:
    post:
      consumes:
      - application/json
      description: 发送邮箱验证码
      parameters:
      - description: 发送验证码请求
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.SendVerifyCodeReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 发送邮箱验证码
      tags:
      - CashierAdmin
  /verifycode/verify:
    post:
      consumes:
      - application/json
      description: 验证邮箱验证码是否正确
      parameters:
      - description: 验证码验证请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.VerifyCodeReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 验证邮箱验证码
      tags:
      - CashierAdmin
swagger: "2.0"
