// Package merchant Code generated by swaggo/swag. DO NOT EDIT
package merchant

import "github.com/swaggo/swag"

const docTemplatemerchant = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/merchant/g2fa/bind": {
            "post": {
                "description": "绑定商户的二次验证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Merchant"
                ],
                "summary": "商户绑定G2FA",
                "parameters": [
                    {
                        "description": "绑定信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.BindG2FAReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "$ref": "#/definitions/inpayos_internal_protocol.Result"
                        }
                    }
                }
            }
        },
        "/merchant/g2fa/new": {
            "post": {
                "description": "为商户生成新的G2FA密钥",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Merchant"
                ],
                "summary": "生成新的G2FA密钥",
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "$ref": "#/definitions/inpayos_internal_protocol.Result"
                        }
                    }
                }
            }
        },
        "/password/change": {
            "post": {
                "description": "商户登录后修改密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Merchant"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改密码请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ChangePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "$ref": "#/definitions/inpayos_internal_protocol.Result"
                        }
                    }
                }
            }
        },
        "/password/reset": {
            "post": {
                "description": "通过邮箱验证码重置密码，新密码将发送到邮箱",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Merchant"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "重置密码请求",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "$ref": "#/definitions/inpayos_internal_protocol.Result"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "邮箱注册新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Merchant"
                ],
                "summary": "商户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inpayos_internal_services.MerchantRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "$ref": "#/definitions/inpayos_internal_protocol.Result"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "inpayos_internal_protocol.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "inpayos_internal_services.MerchantRegisterRequest": {
            "type": "object",
            "required": [
                "company_name",
                "email",
                "nickname",
                "password",
                "phone",
                "verify_code"
            ],
            "properties": {
                "company_name": {
                    "description": "公司名称",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "minLength": 2
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "minLength": 8
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string"
                },
                "reg_ip": {
                    "description": "注册IP",
                    "type": "string"
                },
                "region": {
                    "description": "地区",
                    "type": "string"
                },
                "verify_code": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        },
        "internal_handlers.BindG2FAReq": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "description": "G2FA验证码",
                    "type": "string"
                },
                "verify_code": {
                    "description": "邮箱验证码",
                    "type": "string"
                }
            }
        },
        "internal_handlers.ChangePasswordReq": {
            "type": "object",
            "required": [
                "new_password"
            ],
            "properties": {
                "new_password": {
                    "description": "新密码",
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "internal_handlers.ResetPasswordReq": {
            "type": "object",
            "required": [
                "email",
                "verification_code"
            ],
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "verification_code": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfomerchant holds exported Swagger Info so clients can modify it
var SwaggerInfomerchant = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "merchant",
	SwaggerTemplate:  docTemplatemerchant,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfomerchant.InstanceName(), SwaggerInfomerchant)
}
