definitions:
  inpayos_internal_protocol.Result:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
    type: object
  inpayos_internal_services.MerchantRegisterRequest:
    properties:
      company_name:
        description: 公司名称
        type: string
      email:
        description: 邮箱
        type: string
      nickname:
        description: 昵称
        minLength: 2
        type: string
      password:
        description: 密码
        minLength: 8
        type: string
      phone:
        description: 联系电话
        type: string
      reg_ip:
        description: 注册IP
        type: string
      region:
        description: 地区
        type: string
      verify_code:
        description: 验证码
        type: string
    required:
    - company_name
    - email
    - nickname
    - password
    - phone
    - verify_code
    type: object
  internal_handlers.BindG2FAReq:
    properties:
      code:
        description: G2FA验证码
        type: string
      verify_code:
        description: 邮箱验证码
        type: string
    required:
    - code
    type: object
  internal_handlers.ChangePasswordReq:
    properties:
      new_password:
        description: 新密码
        minLength: 6
        type: string
    required:
    - new_password
    type: object
  internal_handlers.ResetPasswordReq:
    properties:
      email:
        description: 邮箱地址
        type: string
      verification_code:
        description: 验证码
        type: string
    required:
    - email
    - verification_code
    type: object
info:
  contact: {}
paths:
  /merchant/g2fa/bind:
    post:
      consumes:
      - application/json
      description: 绑定商户的二次验证
      parameters:
      - description: 绑定信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.BindG2FAReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 商户绑定G2FA
      tags:
      - Merchant
  /merchant/g2fa/new:
    post:
      consumes:
      - application/json
      description: 为商户生成新的G2FA密钥
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 生成新的G2FA密钥
      tags:
      - Merchant
  /password/change:
    post:
      consumes:
      - application/json
      description: 商户登录后修改密码
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 修改密码请求
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.ChangePasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 修改密码
      tags:
      - Merchant
  /password/reset:
    post:
      consumes:
      - application/json
      description: 通过邮箱验证码重置密码，新密码将发送到邮箱
      parameters:
      - description: 重置密码请求
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.ResetPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 重置密码
      tags:
      - Merchant
  /register:
    post:
      consumes:
      - application/json
      description: 邮箱注册新用户
      parameters:
      - description: 注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/inpayos_internal_services.MerchantRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            $ref: '#/definitions/inpayos_internal_protocol.Result'
      summary: 商户注册
      tags:
      - Merchant
swagger: "2.0"
